server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://119.29.118.44:3306/ibook?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    banner: false